// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQeMfqvBoCMKx-2pQPCwXbTfhhIcvnO8',
    appId: '1:334550068958:web:55340aab3f6f6058ab5c4f',
    messagingSenderId: '334550068958',
    projectId: 'railwaytrackingapp',
    authDomain: 'railwaytrackingapp.firebaseapp.com',
    storageBucket: 'railwaytrackingapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqWD3a273ActXMH4gFjQb_LjTnX7eHYy0',
    appId: '1:334550068958:android:58c6b1f64b4a0d12ab5c4f',
    messagingSenderId: '334550068958',
    projectId: 'railwaytrackingapp',
    storageBucket: 'railwaytrackingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLLV5A5vXQ1HOgkayRG0AYQBcQCf6qGM',
    appId: '1:334550068958:ios:b1d186db9a9e5c08ab5c4f',
    messagingSenderId: '334550068958',
    projectId: 'railwaytrackingapp',
    storageBucket: 'railwaytrackingapp.firebasestorage.app',
    iosBundleId: 'com.example.railwayTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBLLV5A5vXQ1HOgkayRG0AYQBcQCf6qGM',
    appId: '1:334550068958:ios:b1d186db9a9e5c08ab5c4f',
    messagingSenderId: '334550068958',
    projectId: 'railwaytrackingapp',
    storageBucket: 'railwaytrackingapp.firebasestorage.app',
    iosBundleId: 'com.example.railwayTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUQeMfqvBoCMKx-2pQPCwXbTfhhIcvnO8',
    appId: '1:334550068958:web:d33c1b8b3c54a3a0ab5c4f',
    messagingSenderId: '334550068958',
    projectId: 'railwaytrackingapp',
    authDomain: 'railwaytrackingapp.firebaseapp.com',
    storageBucket: 'railwaytrackingapp.firebasestorage.app',
  );
}
